### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by fuelen** [ash-project/spark#86] opened 2024-04-18 08:20 UTC
**Describe the bug**
I have a module that is about 1k LOC, and its compilation time is about 30 sec. I started removing some parts of the code and seems like compilation time is reduced ~linearly with the amount of code I delete.

**To Reproduce**
This file is smaller and takes about 5 sec to compile.
https://github.com/fuelen/seed_factory/blob/main/test/support/schema_example.exs
```sh
$ git clone https://github.com/fuelen/seed_factory
$ echo -e "erlang 26.2.3\nelixir 1.16.2-otp-26" > .tool-versions
$ mise install
$ mix deps.get
$ mix compile
$ cp test/support/schema_example.exs lib/schema_example.ex
$ time mix compile
Compiling 1 file (.ex)
Generated seed_factory app
mix compile  7,21s user 1,49s system 190% cpu 4,563 total

```

**Expected behavior**
Faster compilation

**Runtime**
```
# .tool-versions
erlang 26.2.3
elixir 1.16.2-otp-26
```

 - OS: Arch Linux
 - Spark version: 1.1.55, but 2.1.18 is not faster

**Comment by zachdaniel** [comment] 2024-04-21 19:46
So I'm actually having some trouble tracking down any one cause of a major issue here. I haven't really put significant effort into optimizing large nested DSLs like this. I think that its pretty likely that there are a few big things we can fix, they just aren't immediately apparent to me.

Some examples of what I'm looking for:

1. cases where we are unquoting lots of code into the DSL module itself.
2. cases where we do especially inefficient things w/ the underlying data, particularly around entities as thats what you have a huge amount of here
3. anything that might make us wait on the compiler in weird ways.


I set up a simple example locally in spark tests and used `eflame` to profile things

```elixir
# do it once to warm things up
Module.create(:"SparkTest.Foo#{System.unique_integer([:positive])}", quote do
  use Spark.Test.Contact

    personal_details do
      first_name("Han")
      last_name("Solo")
    end
end, Macro.Env.location(__ENV__))

# generate a flame graph

:eflame.apply(fn ->
Module.create(:"SparkTest.Foo#{System.unique_integer([:positive])}", quote do
  use Spark.Test.Contact

    personal_details do
      first_name("Han")
      last_name("Solo")
      first_name("Han")
      last_name("Solo")
      first_name("Han")
      last_name("Solo")
      first_name("Han")
      last_name("Solo")
      first_name("Han")
      last_name("Solo")
      first_name("Han")
      last_name("Solo")
      first_name("Han")
      last_name("Solo")
      first_name("Han")
    end
end, Macro.Env.location(__ENV__))
end, [])
```
![flame](https://github.com/ash-project/spark/assets/5722339/038d86e8-64a9-4ae6-9c40-1c07be117bfb)


What I was able to see is that the bulk of the time is waiting on the compiler for some reason (its sleeping in a genserver loop at compile time, which in my experience is usually waiting on the code server or something like that).

Some of the things that spark does are practically pathologically strange under the hood, so I'm sure there is plenty of refactoring to be done. The unfortunate thing is that I don't think I'm going to personally have much more time to look into this, at least not for a while. There are ways to split up large DSLs using `Spark.Dsl.Fragment` which may help you here, but otherwise I'm just going to have to leave this open and hope some enterprising soul has some time to dive in and clean up spark's internals and get to the root of this.

**Comment by jckw** [comment] 2024-04-21 22:20
I just contributed to [the bounty on this issue](https://until.dev/bounty/ash-project/spark/86).

Each contribution to this bounty has an expiry time and will be auto-refunded to the contributor if the issue is not solved before then.

This bounty is publicly available and has an 80% share to the PR author set up.

<a href="https://until.dev/bounty/ash-project/spark/86">
  <img src="https://until.dev/api/github/ash-project/spark/86/chart.svg" alt="Current bounty reward" alt="Until bounty reward timeline" />
</a>

This bounty has been made an 80%

**Comment by zachdaniel** [comment] 2024-06-26 23:26
This issue has been resolved "for the most part". It could be faster, but we've seen an improvement on the order of 40s -> 6s to compile any given module. I think we can close this for now, and hunt down additional optimizations in the future.

**Closed by zachdaniel** 2024-06-26 23:26 UTC
Labels: bug
